### ISSUE TITLE
Automatically update path

### ISSUE THREAD

**Issue by aidylewis** [pyenv/pyenv-installer#15] opened 2015-01-06 14:32 UTC
Does the installer purposely not update the path?

``` sh
$ curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
WARNING: seems you still have not added 'pyenv' to the load path.

# Load pyenv automatically by adding
# the following to ~/.bash_profile:

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

CentOS 6.5

Many Thanks

**Comment by yyuu** [comment] 2015-01-13 14:52
At least for now,i t doesn't update any user's shell configuration by design. It should be done by user oneself.

**Comment by obestwalter** [comment] 2015-01-13 15:25
Although I would think that would be  a really good idea to add that as part of the installation. Do you see any major obstacles to add this to the supported shells?

**Comment by yyuu** [comment] 2015-01-13 15:32
@obestwalter We have to handle situation like pyenv-installer#11 to configure user's shell properly. And also, the shell configuration process should be idempotent since users may run the installer script multiple times. I think latter case is somewhat difficult to implement in pure shell script :(

**Comment by obestwalter** [comment] 2015-01-13 15:33
I see ... but I guess, we are not the first ones trying to do that. So I might do some snooping around to get some inspiration how things like that are handled in other projects.

**Comment by obestwalter** [comment] 2015-01-13 15:36
... might be as as easy as sourcing something, then it's pretty clear cut and can be added removed easier. If we can't automate it completely, we can at least provide the script that must be sourced just like with e.g. virtualenvwrapper.

**Comment by obestwalter** [comment] 2015-01-13 22:36
see also suggestions by @jinalskothari in #11

**Comment by shakeelmohamed** [comment] 2015-10-02 07:23
I stole a line out of nvm to do this:

```shell
printf 'export PATH="$HOME/.pyenv/bin:$PATH"\neval "$(pyenv init -)"\neval "$(pyenv virtualenv-init -)"\n' >> ~/.bashrc
```

They also have a lovely [`nvm_detect_profile()`](https://github.com/creationix/nvm/blob/b805de80cb8058f09fecb11786d4d2aec0dac35c/install.sh#L117) function that detects which config file should be modified.

**Comment by aidylewis** [comment] 2015-10-02 09:11
Hi @shakeelmohamed 

Wouldn't we still need to manually source the initialisation file?

**Comment by shakeelmohamed** [comment] 2015-10-04 23:41
@aidylewis sure, NVM doesn't do it:

```shell
 echo "=> Close and reopen your terminal to start using nvm"
```

You'd just have to invoke the following, right?

```shell
. $path_to_profile
```

**Comment by obestwalter** [comment] 2019-01-12 15:07
Closing - no big need and @yyuu doesn't like the idea anyway :)

**Closed by obestwalter** 2019-01-12 15:07 UTC

**Comment by brycedrennan** [comment] 2019-03-26 03:05
Can we have this feature as an optional argument?  The multi-step installation is a real barrier to evangelizing pyenv.

**Comment by jmacdoug007** [comment] 2020-08-12 20:35
I am still getting the same error even though I added 


# Load pyenv automatically by adding
# the following to ~/.bash_profile:

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
